default_platform(:mac)

# https://docs.fastlane.tools/actions/build_mac_app/#automating-the-whole-process
platform :mac do
  desc "Build the release version of the Auto Clicker app"

  lane :release do
    isReleasable = analyze_commits(
      match: '*'
    )

    increment_version_number_in_xcodeproj(
      version_number: lane_context[SharedValues::RELEASE_NEXT_VERSION] # Automatically increment minor version number
    )

    # https://docs.fastlane.tools/actions/build_mac_app/#parameters
    gym(
      scheme: "auto-clicker",
      workspace: "auto-clicker.xcworkspace",
      clean: true,
      output_directory: "build",
      export_method: "mac-application"
    )

    # https://docs.fastlane.tools/actions/commit_version_bump/
    commit_version_bump(
      xcodeproj: "auto-clicker.xcodeproj"
    )

    if isReleasable
      add_git_tag(
        tag: "v#{lane_context[SharedValues::RELEASE_NEXT_VERSION]}"
      )

      push_to_git_remote

      notes = conventional_changelog(
        format: 'markdown',
        title: 'macOS Auto Clicker',
        display_title: false,
        commit_url: 'https://github.com/othyn/macos-auto-clicker/commit',
        sections: {
          feat: ":star2: Features",
          fix: ":bug: Bug Fixes",
          refactor: ":recycle: Code Refactoring",
          perf: ":rocket: Performance Improvements",
          chore: ":wrench: Chores",
          test: ":vertical_traffic_light: Testing",
          docs: ":book: Documentation",
          no_type: ":ghost: Unknown... spooky!"
        }
      )

      sh "node_modules/.bin/create-dmg build/Auto\\ Clicker.app --overwrite build", log: true, error_callback: -> (result) {
        error_occurred = false
      }

      set_github_release(
        repository_name: "othyn/macos-auto-clicker",
        api_bearer: ENV["GITHUB_TOKEN"],
        name: "Release #{lane_context[SharedValues::RELEASE_NEXT_VERSION]}",
        tag_name: "v#{lane_context[SharedValues::RELEASE_NEXT_VERSION]}",
        description: notes,
        commitish: "main",
        upload_assets: ["Auto Clicker #{lane_context[SharedValues::RELEASE_NEXT_VERSION]}.dmg", "Auto Clicker.app.dSYM.zip"]
      )
    else
      print("Not flagged as a release candiate, doing nothing.")
    end
  end
end
