#!/bin/sh

THIS_DIR=$(realpath `dirname $0`)
FRAG_DIR="${THIS_DIR}/fragments"
ICONSET="${THIS_DIR}/AutoClicker.iconset"

echo "[Info] Cleaning existing iconset..."
test -d "${ICONSET}" && rm -r "${ICONSET}"

echo "[Info] Creating shell iconset..."
mkdir "${ICONSET}"

echo "[Info] Building iconset..."
cp   "${FRAG_DIR}/Icon-16.png" "${ICONSET}/icon_16x16.png"
cp   "${FRAG_DIR}/Icon-32.png" "${ICONSET}/icon_16x16@2x.png"
cp   "${FRAG_DIR}/Icon-32.png" "${ICONSET}/icon_32x32.png"
cp   "${FRAG_DIR}/Icon-64.png" "${ICONSET}/icon_32x32@2x.png"
cp  "${FRAG_DIR}/Icon-128.png" "${ICONSET}/icon_128x128.png"
cp  "${FRAG_DIR}/Icon-256.png" "${ICONSET}/icon_128x128@2x.png"
cp  "${FRAG_DIR}/Icon-256.png" "${ICONSET}/icon_256x256.png"
cp  "${FRAG_DIR}/Icon-512.png" "${ICONSET}/icon_256x256@2x.png"
cp  "${FRAG_DIR}/Icon-512.png" "${ICONSET}/icon_512x512.png"
cp "${FRAG_DIR}/Icon-1024.png" "${ICONSET}/icon_512x512@2x.png"

echo "[Info] Creating icns..."
iconutil -c icns "${ICONSET}"

echo "[Info] Cleaning up iconset..."
rm -r "${ICONSET}"

echo "Done!"
